const copy={
  ar:{dir:'rtl',navProfile:'نبذة',navKnowledge:'المعرفة',navResearch:'الأبحاث',eyebrow:'طب العيون · البحث العلمي · التعليم الطبي',lead:'مساحة شخصية منظّمة تجمع الخبرة السريرية، خلاصات المحاضرات، والقراءة النقدية للأدلة في طب العيون.',profileTitle:'نبذة مهنية',profileText:'اختصاصي طب وجراحة العيون بخبرة سريرية وجراحية، واهتمام خاص بأمراض الشبكية والجسم الزجاجي، والذكاء الاصطناعي في تشخيص أمراض القرنية.',knowledgeTitle:'مكتبة المعرفة',retina:'الشبكية والجسم الزجاجي',glaucoma:'الزَرَق',cornea:'القرنية وتصحيح البصر',cataract:'الساد وجراحة العدسة',coming:'المحتوى قيد المراجعة والتصنيف.',researchTitle:'الأبحاث والقراءة النقدية',researchText:'ملخصات علمية تفصل بين نتائج الدراسة وقوة الدليل، مع التركيز على الأهمية السريرية وقابلية التطبيق.',privateReview:'نسخة خاصة للمراجعة'},
  de:{dir:'ltr',navProfile:'Profil',navKnowledge:'Wissen',navResearch:'Forschung',eyebrow:'Augenheilkunde · Forschung · Medizinische Lehre',lead:'Ein strukturierter persönlicher Wissensraum für klinische Erfahrung, Vorlesungsnotizen und kritische Evidenzbewertung in der Augenheilkunde.',profileTitle:'Berufliches Profil',profileText:'Facharzt für Augenheilkunde mit klinischer und operativer Erfahrung sowie besonderem Interesse an Netzhaut- und Glaskörpererkrankungen und KI in der Hornhautdiagnostik.',knowledgeTitle:'Wissensbibliothek',retina:'Netzhaut und Glaskörper',glaucoma:'Glaukom',cornea:'Hornhaut und refraktive Chirurgie',cataract:'Katarakt und Linsenchirurgie',coming:'Inhalt wird geprüft und strukturiert.',researchTitle:'Forschung und kritische Lektüre',researchText:'Wissenschaftliche Zusammenfassungen, die Studienergebnisse von der Evidenzstärke trennen und klinische Relevanz sowie Übertragbarkeit bewerten.',privateReview:'Private Review-Version'},
  en:{dir:'ltr',navProfile:'Profile',navKnowledge:'Knowledge',navResearch:'Research',eyebrow:'Ophthalmology · Research · Medical Education',lead:'A structured personal knowledge space bringing together clinical experience, lecture notes, and critical appraisal of ophthalmic evidence.',profileTitle:'Professional profile',profileText:'Ophthalmologist with clinical and surgical experience, focusing on retinal and vitreous disease and artificial intelligence in corneal diagnostics.',knowledgeTitle:'Knowledge library',retina:'Retina and vitreous',glaucoma:'Glaucoma',cornea:'Cornea and refractive surgery',cataract:'Cataract and lens surgery',coming:'Content is being reviewed and organized.',researchTitle:'Research and critical appraisal',researchText:'Scientific summaries that separate study findings from certainty of evidence, with emphasis on clinical relevance and applicability.',privateReview:'Private review version'}
};
const selector=document.querySelector('#language-select');
function setLanguage(language){const selected=copy[language];document.documentElement.lang=language;document.documentElement.dir=selected.dir;document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=selected[node.dataset.i18n]);localStorage.setItem('language',language)}
selector.addEventListener('change',event=>setLanguage(event.target.value));
const saved=localStorage.getItem('language')||'ar';selector.value=saved;setLanguage(saved);

